health_checker:
  ros__parameters:
    platform:
      motor: "/motorOK"
      battery: "/batteryOK"
    manual_controllers:
      local_controller_topic: "/local_joy/joy"
      telop_controller_topic: "/telop_joy/joy"
    requirements:
      telop:
        fpv_camera:
      autonomy:
        lidar:
        camera1:
        camera2:

  